// <auto-generated />
using Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215153424_AdicaoClienteEServico")]
    partial class AdicaoClienteEServico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    b.HasKey("Id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Freelancer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("fre_id");

                    b.HasKey("Id");

                    b.ToTable("freelancers");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ser_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ser_descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ser_nome");

                    b.Property<int>("clientes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("clientes");

                    b.ToTable("servicos");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("text")
                        .HasColumnName("usu_foto_perfil_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_nome");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("Backend.Domain.Entities.Cliente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_clientes_usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Freelancer", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Freelancer")
                        .HasForeignKey("Backend.Domain.Entities.Freelancer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_freelancers_usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Servico", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Servicos")
                        .HasForeignKey("clientes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Freelancer");
                });
#pragma warning restore 612, 618
        }
    }
}
