// <auto-generated />
using System;
using Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("adl_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adl_action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adl_changes");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("adl_datetime");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adl_entity_name");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adl_user");

                    b.HasKey("Id");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("Backend.Domain.Entities.BandeiraCartaoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bcc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bcc_nome");

                    b.HasKey("Id");

                    b.ToTable("bandeiras_cartao_credito");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Mastercard"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Visa"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Elo"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "American Express"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Hipercard"
                        });
                });

            modelBuilder.Entity("Backend.Domain.Entities.CartaoCredito", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("cre_id");

                    b.Property<int>("BandeiraId")
                        .HasColumnType("integer")
                        .HasColumnName("cre_bcc_id");

                    b.Property<string>("CodigoSeguranca")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("cre_codigo_seguranca");

                    b.Property<string>("NomeImpresso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cre_nome_impresso");

                    b.HasKey("Id");

                    b.HasIndex("BandeiraId");

                    b.ToTable("cartoes_credito");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    b.HasKey("Id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("con_id");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("con_agencia");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("con_banco");

                    b.Property<string>("CpfTitular")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("con_cpf_titular");

                    b.Property<string>("NomeTitular")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("con_nome_titular");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("con_numero_conta");

                    b.Property<int>("TipoContaId")
                        .HasColumnType("integer")
                        .HasColumnName("con_tpc_id");

                    b.HasKey("Id");

                    b.HasIndex("TipoContaId");

                    b.ToTable("contas_bancarias");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Freelancer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("fre_id");

                    b.Property<string>("DescricaoPerfil")
                        .HasColumnType("text")
                        .HasColumnName("fre_descricao_perfil");

                    b.Property<string>("Titulo")
                        .HasColumnType("text")
                        .HasColumnName("fre_titulo");

                    b.HasKey("Id");

                    b.ToTable("freelancers");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ProjetoDestacadoProposta", b =>
                {
                    b.Property<int>("ProjetoFreelancerId")
                        .HasColumnType("integer")
                        .HasColumnName("pde_prj_id");

                    b.Property<int>("PropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("pde_pro_id");

                    b.HasKey("ProjetoFreelancerId", "PropostaId");

                    b.HasIndex("PropostaId");

                    b.ToTable("projetos_destacados_proposta");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ProjetoFreelancer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pjf_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("pjf_descricao");

                    b.Property<int>("FreelancerId")
                        .HasColumnType("integer")
                        .HasColumnName("pjf_fre_id");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("text")
                        .HasColumnName("pjf_imagem_url");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("pjf_link");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pjf_nome");

                    b.HasKey("Id");

                    b.HasIndex("FreelancerId");

                    b.ToTable("projetos_freelancer");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Proposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pro_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FreelancerId")
                        .HasColumnType("integer")
                        .HasColumnName("pro_fre_id");

                    b.Property<string>("ItensPropostos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pro_itens_propostos");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pro_mensagem");

                    b.Property<DateTime>("PrazoEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pro_prazo_entrega");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("pro_ser_id");

                    b.Property<bool>("TaxaSistemaAdicionadaAoTotal")
                        .HasColumnType("boolean")
                        .HasColumnName("pro_taxa_sistema_adicionada_ao_total");

                    b.Property<decimal>("ValorPorHora")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("pro_valor_por_hora");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pro_valor_total");

                    b.HasKey("Id");

                    b.HasIndex("FreelancerId");

                    b.HasIndex("ServicoId");

                    b.ToTable("propostas");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ser_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("ser_cli_id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ser_descricao");

                    b.Property<bool>("IsEntregue")
                        .HasColumnType("boolean")
                        .HasColumnName("ser_is_entregue");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ser_nome");

                    b.Property<bool>("OrcamentoIsAberto")
                        .HasColumnType("boolean")
                        .HasColumnName("ser_orcamento_is_aberto");

                    b.Property<DateTime>("Prazo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ser_prazo");

                    b.Property<int?>("PropostaAceitaId")
                        .HasColumnType("integer")
                        .HasColumnName("ser_proposta_aceita_id");

                    b.Property<decimal>("ValorMinimo")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("ser_valor_minimo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PropostaAceitaId")
                        .IsUnique();

                    b.ToTable("servicos");
                });

            modelBuilder.Entity("Backend.Domain.Entities.TipoConta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tpc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tpc_nome");

                    b.HasKey("Id");

                    b.ToTable("tipos_conta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Corrente"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Poupança"
                        });
                });

            modelBuilder.Entity("Backend.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_email");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("text")
                        .HasColumnName("usu_foto_perfil_url");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_hash_senha");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("usu_is_admin");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_nome");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Cpf = "00000000000",
                            Email = "admin@sistema.com",
                            FotoPerfilUrl = "uploads/fotos-perfil/fotoADM.jpg",
                            HashSenha = "AQAAAAIAAYagAAAAEHEM/Yc24Gwy0usv3Q4hrhUuLkyawKFjak/+t9BLGQo+9o5ziRkt7Rel7X6oHFVYOw==",
                            IsAdmin = true,
                            Nome = "Administrador do Sistema"
                        });
                });

            modelBuilder.Entity("Backend.Domain.Entities.CartaoCredito", b =>
                {
                    b.HasOne("Backend.Domain.Entities.BandeiraCartaoCredito", "Bandeira")
                        .WithMany("CartoesCredito")
                        .HasForeignKey("BandeiraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cre_bcc");

                    b.HasOne("Backend.Domain.Entities.Cliente", "Cliente")
                        .WithOne("CartaoCredito")
                        .HasForeignKey("Backend.Domain.Entities.CartaoCredito", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bandeira");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("Backend.Domain.Entities.Cliente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cli_usu");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ContaBancaria", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Freelancer", "Freelancer")
                        .WithOne("ContaBancaria")
                        .HasForeignKey("Backend.Domain.Entities.ContaBancaria", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.TipoConta", "TipoConta")
                        .WithMany("ContasBancarias")
                        .HasForeignKey("TipoContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_con_tpc");

                    b.Navigation("Freelancer");

                    b.Navigation("TipoConta");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Freelancer", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Freelancer")
                        .HasForeignKey("Backend.Domain.Entities.Freelancer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fre_usu");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ProjetoDestacadoProposta", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ProjetoFreelancer", "ProjetoFreelancer")
                        .WithMany("ProjetosDestacados")
                        .HasForeignKey("ProjetoFreelancerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pde_prj");

                    b.HasOne("Backend.Domain.Entities.Proposta", "Proposta")
                        .WithMany("ProjetosDestacados")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pde_pro");

                    b.Navigation("ProjetoFreelancer");

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ProjetoFreelancer", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Freelancer", "Freelancer")
                        .WithMany("ProjetosFreelancer")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prj_fre");

                    b.Navigation("Freelancer");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Proposta", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Freelancer", "Freelancer")
                        .WithMany("Propostas")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pro_fre");

                    b.HasOne("Backend.Domain.Entities.Servico", "Servico")
                        .WithMany("Propostas")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pro_ser");

                    b.Navigation("Freelancer");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Servico", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Servicos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ser_cli");

                    b.HasOne("Backend.Domain.Entities.Proposta", "PropostaAceita")
                        .WithOne("ServicoOndeFoiAceita")
                        .HasForeignKey("Backend.Domain.Entities.Servico", "PropostaAceitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ser_pro_aceita");

                    b.Navigation("Cliente");

                    b.Navigation("PropostaAceita");
                });

            modelBuilder.Entity("Backend.Domain.Entities.BandeiraCartaoCredito", b =>
                {
                    b.Navigation("CartoesCredito");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("CartaoCredito");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Freelancer", b =>
                {
                    b.Navigation("ContaBancaria");

                    b.Navigation("ProjetosFreelancer");

                    b.Navigation("Propostas");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ProjetoFreelancer", b =>
                {
                    b.Navigation("ProjetosDestacados");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Proposta", b =>
                {
                    b.Navigation("ProjetosDestacados");

                    b.Navigation("ServicoOndeFoiAceita");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Servico", b =>
                {
                    b.Navigation("Propostas");
                });

            modelBuilder.Entity("Backend.Domain.Entities.TipoConta", b =>
                {
                    b.Navigation("ContasBancarias");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Freelancer");
                });
#pragma warning restore 612, 618
        }
    }
}
