// <auto-generated />
using System;
using Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219205705_AddAuditLog")]
    partial class AddAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Backend.Domain.Entities.BandeiraCartaoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bcc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bcc_nome");

                    b.HasKey("Id");

                    b.ToTable("bandeiras_cartao_credito");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Mastercard"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Visa"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Elo"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "American Express"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Hipercard"
                        });
                });

            modelBuilder.Entity("Backend.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    b.HasKey("Id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("con_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("con_agencia");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("con_banco");

                    b.Property<string>("CpfTitular")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("con_cpf_titular");

                    b.Property<int>("FreelancerId")
                        .HasColumnType("integer")
                        .HasColumnName("con_fre_id");

                    b.Property<string>("NomeTitular")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("con_nome_titular");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("con_numero_conta");

                    b.Property<int>("TipoContaId")
                        .HasColumnType("integer")
                        .HasColumnName("con_tpc_id");

                    b.HasKey("Id");

                    b.HasIndex("FreelancerId")
                        .IsUnique();

                    b.HasIndex("TipoContaId");

                    b.ToTable("contas_bancarias");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Freelancer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("fre_id");

                    b.Property<string>("DescricaoPerfil")
                        .HasColumnType("text")
                        .HasColumnName("fre_descricao_perfil");

                    b.Property<string>("Titulo")
                        .HasColumnType("text")
                        .HasColumnName("fre_titulo");

                    b.HasKey("Id");

                    b.ToTable("freelancers");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ProjetoFreelancer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pjf_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("pjf_descricao");

                    b.Property<int>("FreelancerId")
                        .HasColumnType("integer")
                        .HasColumnName("pjf_fre_id");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("text")
                        .HasColumnName("pjf_imagem_url");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("pjf_link");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pjf_nome");

                    b.HasKey("Id");

                    b.HasIndex("FreelancerId");

                    b.ToTable("projetos_freelancer");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ser_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("ser_cli_id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ser_descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ser_nome");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("servicos");
                });

            modelBuilder.Entity("Backend.Domain.Entities.TipoConta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tpc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tpc_nome");

                    b.HasKey("Id");

                    b.ToTable("tipos_conta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Corrente"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Poupança"
                        });
                });

            modelBuilder.Entity("Backend.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_email");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("text")
                        .HasColumnName("usu_foto_perfil_url");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_hash_senha");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("usu_is_admin");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_nome");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("Backend.Domain.Entities.Cliente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_clientes_usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ContaBancaria", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Freelancer", "Freelancer")
                        .WithOne("ContaBancaria")
                        .HasForeignKey("Backend.Domain.Entities.ContaBancaria", "FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.TipoConta", "TipoConta")
                        .WithMany()
                        .HasForeignKey("TipoContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("TipoConta");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Freelancer", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Freelancer")
                        .HasForeignKey("Backend.Domain.Entities.Freelancer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_freelancers_usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ProjetoFreelancer", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Freelancer", "Freelancer")
                        .WithMany("ProjetosFreelancer")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Freelancer");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Servico", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Servicos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Freelancer", b =>
                {
                    b.Navigation("ContaBancaria");

                    b.Navigation("ProjetosFreelancer");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Freelancer");
                });
#pragma warning restore 612, 618
        }
    }
}
