classDiagram

class Usuarios {
    +Integer id
    +String nome
    +String cpf
    +String email
    +String foto_perfil_url
    +String hash_senha
    +Boolean isAdmin
}

class Freelancers {
    +Integer id
    +String descricao_perfil
    +String titulo
}

class Clientes {
    +Integer id
}

class Propostas {
    +Integer id
    +Integer idFrelancer
    +Integer idServico
    +Numeric valor_por_hora
    +Date orcamento_de_tempo
    +String mensagem
    +String itens_propostos
    +Integer valorTotal
    +Boolean taxa_sistema_adicionada_ao_total
}

class Servicos {
    +Integer id
    +Integer idCliente
    +String nome
    +String descricao
    +Numeric orcamento
    +Date prazo
    +Numeric valor_minimo
    +Integer proposta_aceita_id
}

class ProjetosFreelancer {
    +Integer id
    +Integer idFrelancer
    +String nome
    +String descricao
    +String imagem_url
    +String link
}

class CartoesCredito {
    +Integer id
    +String nomeImpresso
    +Integer idBandeira
    +String codigoSeguranca
    +Integer idCartao
}

class Avaliacoes {
    +Integer id
    +Integer idUsuario
    +Integer nota_estrelas
    +String comentario
}

class Pagamentos {
    +Integer id
    +Integer idCartao
    +Integer idServico
    +Numeric valor
}

class MensagensServico {
    +Integer id
    +Integer idServico
    +Date data
    +String mensagem
    +Integer idRemetente
    +Integer idDestinatario
}

class BandeirasCartaoCredito {
    +Integer id
    +String ome
}

%% ========================
%% RELACIONAMENTOS
%% ========================

Usuarios "1" <|-- "1" Freelancers : extends
Usuarios "1" <|-- "1" Clientes : extends

Freelancers "1" --> "0..*" Propostas : faz
Clientes "1" --> "0..*" Servicos : cria

Servicos "1" --> "0..*" Propostas : recebe
Propostas "0..1" --> "1" Servicos : aceita

Freelancers "1" --> "0..*" ProjetosFreelancer : possui
ProjetosFreelancer "0..*" --> "0..*" Propostas : destacado_em

Usuarios "1" --> "0..*" CartoesCredito
CartoesCredito "1" --> "0..*" Pagamentos
Servicos "1" --> "0..*" Pagamentos

Usuarios "1" --> "0..*" Avaliacoes

Servicos "1" --> "0..*" MensagensServico
Usuarios "1" --> "0..*" MensagensServico : remetente
Usuarios "1" --> "0..*" MensagensServico : destinatario

BandeirasCartaoCredito "1" --> "0..*" CartoesCredito

  