CREATE TABLE IF NOT EXISTS "usuarios" (
	"usu_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"usu_nome" VARCHAR(255) NOT NULL,
	"usu_cpf" CHAR(11) NOT NULL,
	"usu_email" VARCHAR(255) NOT NULL,
	"usu_foto_perfil" MACADDR,
	-- A
	"usu_senha" VARCHAR(255) NOT NULL,
	PRIMARY KEY("usu_id")
);


COMMENT ON COLUMN "usuarios"."usu_senha" IS 'A';


CREATE TABLE IF NOT EXISTS "freelancers" (
	"fre_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fre_descricao" TEXT,
	"fre_titulo" VARCHAR(255),
	"fre_ranking" INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("fre_id")
);




CREATE TABLE IF NOT EXISTS "clientes" (
	"cli_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	PRIMARY KEY("cli_id")
);




CREATE TABLE IF NOT EXISTS "propostas" (
	"pro_id" INTEGER NOT NULL,
	"pro_fre_id" INTEGER NOT NULL,
	"pro_ser_id" INTEGER NOT NULL,
	"pro_valor_por_hora" NUMERIC(5,0) NOT NULL,
	"pro_mensagem" TEXT NOT NULL,
	"pro_itens_propostos" TEXT NOT NULL,
	"pro_contraproposta" TEXT,
	PRIMARY KEY("pro_id")
);




CREATE TABLE IF NOT EXISTS "servicos" (
	"ser_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"ser_cli_id" INTEGER NOT NULL,
	"ser_descricao" TEXT NOT NULL,
	"ser_orcamento" ,
	"ser_prazo" TIMESTAMPTZ NOT NULL,
	"ser_valor_minimo" NUMERIC(6,2) NOT NULL,
	PRIMARY KEY("ser_id")
);




CREATE TABLE IF NOT EXISTS "projetos_freelancer" (
	"prj_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"prj_fre_id" INTEGER NOT NULL,
	"prj_nome" VARCHAR(255) NOT NULL,
	"prj_descricao" TEXT,
	"prj_imagem" ,
	"prj_link" VARCHAR(255),
	PRIMARY KEY("prj_id")
);




CREATE TABLE IF NOT EXISTS "cartoes_credito" (
	"cre_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"cre_nome_impresso" VARCHAR(255) NOT NULL,
	"cre_bandeira"  NOT NULL,
	"cre_codigo_seguranca" CHAR(3) NOT NULL,
	"cre_usu_id" INTEGER NOT NULL,
	PRIMARY KEY("cre_id")
);




CREATE TABLE IF NOT EXISTS "avaliacoes" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "projetos_destacados_proposta" (
	"pdp_prj_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"pdp_pro_id" INTEGER,
	PRIMARY KEY("pdp_prj_id")
);




CREATE TABLE IF NOT EXISTS "pagamento" (
	"pag_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"pag_cre_id" INTEGER NOT NULL,
	"pag_ser_id" INTEGER NOT NULL,
	"pag_valor" NUMERIC(6,2) NOT NULL,
	PRIMARY KEY("pag_id")
);




CREATE TABLE IF NOT EXISTS "mensagens_servico" (
	"mss_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"mss_ser_id" INTEGER NOT NULL,
	"mss_data" TIMESTAMPTZ NOT NULL,
	"mss_mensagem" TEXT NOT NULL,
	PRIMARY KEY("mss_id")
);




CREATE TABLE IF NOT EXISTS "denuncias" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	PRIMARY KEY("id")
);



ALTER TABLE "freelancers"
ADD FOREIGN KEY("fre_id") REFERENCES "usuarios"("usu_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "clientes"
ADD FOREIGN KEY("cli_id") REFERENCES "usuarios"("usu_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "propostas"
ADD FOREIGN KEY("pro_ser_id") REFERENCES "servicos"("ser_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "propostas"
ADD FOREIGN KEY("pro_fre_id") REFERENCES "freelancers"("fre_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "servicos"
ADD FOREIGN KEY("ser_cli_id") REFERENCES "clientes"("cli_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "projetos_freelancer"
ADD FOREIGN KEY("prj_fre_id") REFERENCES "freelancers"("fre_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "projetos_destacados_proposta"
ADD FOREIGN KEY("pdp_prj_id") REFERENCES "projetos_freelancer"("prj_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "projetos_destacados_proposta"
ADD FOREIGN KEY("pdp_pro_id") REFERENCES "propostas"("pro_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "cartoes_credito"
ADD FOREIGN KEY("cre_usu_id") REFERENCES "usuarios"("usu_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pagamento"
ADD FOREIGN KEY("pag_cre_id") REFERENCES "cartoes_credito"("cre_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pagamento"
ADD FOREIGN KEY("pag_ser_id") REFERENCES "servicos"("ser_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "mensagens_servico"
ADD FOREIGN KEY("mss_ser_id") REFERENCES "servicos"("ser_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;